version: "3.8"

services:
  jenkins:
    image: myjenkins-blueocean:2.516.1-1
    container_name: jenkins-blueocean
    privileged: true
    user: "jenkins:$(id -g docker)"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - microservices-network

  catalog-db:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - microservices-network

  # Optional: Add more databases for other services
  # order-db:
  #   image: postgres:16-alpine
  #   container_name: order-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=orderdb
  #   ports:
  #     - "15433:5432"
  #   volumes:
  #     - order_db_data:/var/lib/postgresql/data
  #   networks:
  #     - microservices-network

volumes:
  jenkins_home:
    driver: local
  catalog_db_data:
    driver: local
  # order_db_data:
  #   driver: local

networks:
  microservices-network:
    driver: bridge