version: "3.8"
name: 'spring-boot-microservicees'

services:
  jenkins:
    image: myjenkins-blueocean:2.516.1-1
    container_name: jenkins-blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    # This volume mount is the key to solving the Docker-in-Docker issue.
    # It exposes the host's Docker socket to the Jenkins container, allowing
    # Jenkins to communicate with the Docker daemon and start other containers.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <--- This is the key fix
      - jenkins_home:/var/jenkins_home
    deploy:
      resources:
        limits:
          memory: 4g

  catalog-db:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

volumes:
  jenkins_home:
    driver: local