name: Catalog Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'catalog-service/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify
